### ISSUE TITLE
Render dc.barChart in Node.js

### ISSUE THREAD

**Issue by fernandrez** [dc-js/dc-node#1]
Good day I have the following code to try to render a Bar Chart from Node.js using Express Framework and JSDOM:

``` js
var express = require('express');
var router = express.Router();
var d3 = require('d3');
var d3request = require('d3-request');
var jsdom = require('jsdom');
global.d3_document = jsdom.jsdom();
var dc = require('dc');

/* GET bar for specific dataframe with given dimensions. */
router.get('/:dftitle/:xdim/:ydim/', function(req, res, next) {
  /* Use d3-request to get the data */ 
  d3request.tsv("http://localhost:3000/data/data.tsv", function(d){
    d.pay = +d.pay;
    d.bal = +d.bal;
    return d;
  }, function(data){
    const containerSelector = 'bar-chart-container';
    var htmlStub = '<html><head>Hello</head><body><div id="'+containerSelector+'"></div></body></html>';
    //Render the Chart
    jsdom.env({ features : { QuerySelector : true }, html : htmlStub
      , done : function(errors, window) {
        bcc = window.document.querySelector(containerSelector);
        global.d3_document = window.document;
        var BarChart = dc.barChart(bcc);
        console.log(BarChart);
        res.send(jsdom.serializeDocument(window.document));
      }
    });
  });
});

module.exports = router;
```

Its failing exactly at `var BarChart = dc.barChart(bcc);` with the error:

```
/usr/local/src/node/s3d3c/node_modules/d3/d3.js:1312
d3_behavior_zoomWheel = "onwheel" in d3_document ? (d3_behavior_zoomDelta = function() {
^

TypeError: Cannot use 'in' operator to search for 'onwheel' in undefined
at Object.d3.behavior.zoom (/usr/local/src/node/s3d3c/node_modules/d3/d3.js:1312:44)
at Object.dc.coordinateGridMixin (/usr/local/src/node/s3d3c/node_modules/dc/dc.js:2760:29)
at Object.dc.barChart (/usr/local/src/node/s3d3c/node_modules/dc/dc.js:5277:35)
at Object.jsdom.env.done (/usr/local/src/node/s3d3c/routes/bars.js:25:27)
at /usr/local/src/node/s3d3c/node_modules/jsdom/lib/jsdom.js:275:18
at nextTickCallbackWith0Args (node.js:453:9)
at process._tickCallback (node.js:382:13)
```

Is it possible for this chart to be rendered server side using JSDOM? How does this library work? Can you help me out please?

**Comment by fernandrez** [comment]
Thank you so these are truly connected. Does anybody know how to perform this rendering from Node.js/Express/JSDOM?

**Comment by gordonwoodhull** [comment]
I know that `dc-node` once worked, but I've never seen a complete example, sorry. It looks like you are trying to initialize `d3_document` when that's actually a private variable of d3, which it [initializes from `this.document`](https://github.com/mbostock/d3/blob/master/d3.js#L8). 

I don't know what `this` is in a Node context, but that would be the way to get past this.

If you do manage to produce a working example, please consider contributing it on [the wiki](https://github.com/dc-js/dc-node/wiki) for this project.

**Comment by fernandrez** [comment]
Will work on this tomorrow. Thank you @gordonwoodhull, appreciate your time.

**Comment by fernandrez** [comment]
This was completed using the libraries defined in the window variable inside jsdom htmlStub similar to the following:

``` js
/* GET bar for specific dataframe with given dimensions. Rendered on server.*/
router.get('/s/s/r/:dftitle/:dim/:group/', function(req, res, next) {
  var t0=process.hrtime(); var t1=process.hrtime();
  console.log((t1[0]+t1[1]*1e-9)-(t0[0]+t0[1]*1e-9));
  /* Use d3-request to get the data */
  d3.tsv("http://"+process.env.HOSTNAME+".domain.com:"+process.env.PORT+"/data/data.tsv", function(d){
    d.pay = +d.pay;
    d.bal = +d.bal;
    return d;
  }, function(data){
    const containerSelector = 'chart-container';
    var htmlStub = 'html<html><head><link rel="stylesheet" type="text/css" href="https://dc-js.github.io/dc.js/css/dc.css"/></head><body><div id="'+containerSelector+'"></div></body></html>';
    //Render the Chart
    t0=t1; t1=process.hrtime();
    console.log((t1[0]+t1[1]*1e-9)-(t0[0]+t0[1]*1e-9));
    jsdom.env({ features : { QuerySelector : true },
        scripts: [
                  "https://dc-js.github.io/dc.js/js/d3.js",
                  "https://dc-js.github.io/dc.js/js/crossfilter.js",
                  "https://dc-js.github.io/dc.js/js/dc.js"
                 ],
        html : htmlStub,
        done : function(errors, window) {

          t0=t1; t1=process.hrtime();
          console.log((t1[0]+t1[1]*1e-9)-(t0[0]+t0[1]*1e-9));
          bcc = window.document.querySelector('#'+containerSelector);
          var chart = window.dc.barChart(bcc);
          var crossData = crossfilter(data);
          var dimension = crossData.dimension(function(d){
            return d[req.dim];
          });
          var group = dimension.group().reduceSum(function(d){
            return d[req.group];
          });

          chart
            .transitionDuration(0)
            .width(500)
            .height(300)
            .x(window.d3.scale.ordinal())
            .xUnits(window.dc.units.ordinal)
            .dimension(dimension)
            .group(group)
            .elasticY(true)
            .valueAccessor(function(p) {return p.value;});

          t0=t1; t1=process.hrtime();
          console.log((t1[0]+t1[1]*1e-9)-(t0[0]+t0[1]*1e-9));
          window.dc.renderAll();

          t0=t1; t1=process.hrtime();
          console.log((t1[0]+t1[1]*1e-9)-(t0[0]+t0[1]*1e-9));
          res.send(jsdom.serializeDocument(window.document));
      }
    });
  });
});
```

**Comment by gordonwoodhull** [comment]
Oh wow, that's pretty fascinating. 

Glad you got this working, and thanks for reporting how you did it!

**Comment by fernandrez** [comment]
Thank you @gordonwoodhull for your time. My pleasure.
